create table events (event_id int8 generated by default as identity, uploadDate date, file_id int8, user_id int8, primary key (event_id));
create table files (file_id int8 generated by default as identity, path varchar(255), event_id int8, primary key (file_id));
create table users (user_id int8 generated by default as identity, firstname varchar(255), lastname varchar(255), primary key (user_id));
alter table if exists events add constraint FKav02cmkm91xjn1e1euy2w39ht foreign key (file_id) references files;
alter table if exists events add constraint FKat8p3s7yjcp57lny4udqvqncq foreign key (user_id) references users;
alter table if exists files add constraint FKeitemc76qh2qouafitttwdaan foreign key (event_id) references events;